version: '2'
services:
  app:
    build: ./app/
    container_name: url-shortener-app
    depends_on:
      - database
    ports:
      - 8081:8081
  nginx:
    image: nginx
    container_name: url-shortener-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8090:8090
  database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - 'C:/data/db:/data/db'