version: '2'
services:
  app:
    build: ./app/
    container_name: url-shortener-app
    depends_on:
      - database
    ports:
      - 8081:8081
  nginx:
    image: nginx
    container_name: url-shortener-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8090:8090
  database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - '/data/mongodb:/data/db'
  kgs:
    build: ./kgs-web/
    container_name: url-shortener-kgs
    depends_on:
      - database-kgs
    ports:
      - 9091:9091
  database-kgs:
    image: postgres
    restart: always
    volumes:
      - '/data/postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: pwd123
    ports:
      - 5432:5432